[project]
name = "anti-fraud-real-time-transactions"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Vagner Michell", email = "vagner.michell@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "faker>=40.37.0",
    "pycountry>=26.2.16",
    "requests>=2.34.2",
    "uvicorn[standard]>=0.52.4",
]


[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[tool.uv]
package = false

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
    "pytest>=9.1.1",
    "ruff>=0.16.7",
]
