name: CI

on:
  push:
     tags:
      - "v*"
  pull_request:

permissions:
  contents: read
  packages: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d

      - name: Instalar dependências
        run: uv sync

      - name: Verificar formatação
        run: uv run ruff format --check .

      - name: Rodar lint
        run: uv run ruff check .

      - name: Rodar testes
        run: uv run python -m pytest

  docker:
      runs-on: ubuntu-latest

      steps:
        - name: Baixar código
          uses: actions/checkout@v4

        - name: Login no GHCR
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Build da imagem Docker
          run: |
            docker build \
              -t ghcr.io/michellvagner/anti-fraud-real-time-transactions:latest \
              -t ghcr.io/michellvagner/anti-fraud-real-time-transactions:${{ github.sha }} \
              -t ghcr.io/michellvagner/anti-fraud-real-time-transactions:${{ github.ref_name }} .

        - name: Push da imagem Docker
          run: |
            docker push ghcr.io/michellvagner/anti-fraud-real-time-transactions:latest
            docker push ghcr.io/michellvagner/anti-fraud-real-time-transactions:${{ github.sha }}
            docker push ghcr.io/michellvagner/anti-fraud-real-time-transactions:${{ github.ref_name }}