name: CI

on:
  push:
  pull_request:

permissions:
  contents: write
  pull-requests: write
  packages: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d

      - name: Instalar dependências
        run: uv sync

      - name: Verificar formatação
        run: uv run ruff format --check .

      - name: Rodar lint
        run: uv run ruff check .

      - name: Rodar testes
        run: uv run python -m pytest

  docker:
      runs-on: ubuntu-latest

      steps:
        - name: Baixar código
          uses: actions/checkout@v4

        - name: Login no GHCR
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Build da imagem Docker
          run: |
            docker build \
              -t ghcr.io/michellvagner/anti-fraud-real-time-transactions:latest \
              -t ghcr.io/michellvagner/anti-fraud-real-time-transactions:${{ github.sha }} .

        - name: Push da imagem Docker
          run: |
            docker push ghcr.io/michellvagner/anti-fraud-real-time-transactions:latest
            docker push ghcr.io/michellvagner/anti-fraud-real-time-transactions:${{ github.sha }}

  release-please:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest

    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}

    steps:
      - name: Release Please
        id: release
        uses: googleapis/release-please-action@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: python
          
  docker-release:
    needs: release-please
    if: needs.release-please.outputs.release_created == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código da release
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.release-please.outputs.tag_name }}

      - name: Login no GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build da imagem Docker da release
        run: |
          docker build \
            -t ghcr.io/michellvagner/anti-fraud-real-time-transactions:${{ needs.release-please.outputs.tag_name }} .

      - name: Push da imagem Docker da release
        run: |
          docker push ghcr.io/michellvagner/anti-fraud-real-time-transactions:${{ needs.release-please.outputs.tag_name }}